### ISSUE TITLE
Add baseline calling method as is

### ISSUE THREAD

**Issue by dzmitry-lahoda** [seesharper/ProxyBenchmarks#4]
Add baseline calling method as is from manually written proxy. Mark method called and proxy method which calls with `MethodImplOptions.NoInlining | MethodImplOptions.NoOptimization` so these are not eliminated.

**Comment by dzmitry-lahoda** [comment]
New way of declaring classes and lambda expression bodied method allow to write manual proxies faster. And the functional notion of interface segregation principle leads to smaller interfaces. So proxy generators are less needed.

**Comment by seesharper** [comment]
Great job @dzmitry-lahoda  👍 We needed that baseline to emphasise the overhead of doing dynamic proxies.  

As for performance, I would never use a dynamic proxy in a tight loop. But I would maybe use it to implement a system wide diagnostic tool that can be turned on and off by config. Sort of like a intercept all/profiling kind of thing. In the request pipeline of a web server it would probably not matter all that much. We are talking about 30ns per request and our typical average web request might be in the 30 to 50ms range. Is it negligible? Well, that is up to all of us making decisions about these things 😎

**Comment by seesharper** [comment]
Closed by #5

**Comment by dzmitry-lahoda** [comment]
There faster proxy is the more times people will use as always on feature in more situations. I.e. Hegel-Marx  move from quantity(faster) to quality(new usages).
